/**
 * Created by Administrator on 2017/5/12.
 */
lg = (function(){
    var langue={common_header_index:"首页",
        common_header_competition_center:"竞猜中心",
        common_header_competition:"竞猜",
        common_header_video:"视频中心",
        common_header_data:"资料库",
        common_header_store:"商城",
        common_header_service:"客服中心",
        common_header_log_in:"登录",
        common_header_personal:"个人中心",
        common_header_language:"语言选择",
        common_header_regist:"注册",
        common_header_log_out:"退出",
        common_footer_index:"首页",
        common_footer_football:"足球比分",
        common_footer_basketball:"篮球比分",
        common_footer_exponent:"指数中心",
        common_footer_data:"资料库",
        common_footer_video:"视频直播",
        common_footer_kj:"开奖结果",
        common_footer_trend:"走势图表",
        common_footer_service:"客服系统",
        common_footer_ly:"关于乐盈",
        common_footer_icpo:"ICP主体备案号",
        common_footer_icps:"粤ICP备15041803号-1",
        common_footer_icpt:"粤ICP备15041803号-2",
        common_footer_rights:"版权所有",
        common_footer_company:"深圳华海乐盈网络科技有限公司",
        common_button_confirm:"确 定",
        common_button_cancel:"取 消",
        common_button_previous:"上一页",
        common_button_next:"下一页",
        common_words_di:"第",
        common_words_ye:"页",
        common_words_nodata:"暂无数据",
        common_words_soon:"敬请期待",
        index_title_news:"赛事资讯",
        index_title_schedule:"近期赛程",
        index_title_time:"时间",
        index_title_team:"战队",
        index_title_score:"比分",
        index_title_video:"观看记录",
        index_button_more:"更多",
        index_button_more_match:"更多赛事",
        index_button_video:"观看记录",
        index_button_detail:"点击查看详情",
        index_button_competition:"比赛竞猜",
        index_words_month:"个月以前",
        index_words_day:"天以前",
        index_words_hour:"小时以前",
        index_words_minute:"分钟以前",
        index_words_no_match:"暂无赛事数据",
        index_words_news:"新闻",
        index_words_select:"选择赛事",
        index_title_status:"状态",
        index_title_number:"胜数",
        index_title_match:"赛事",
        index_title_view:"观看",
        index_words_unplayed:"未开始",
        index_words_end:"已结束",
        league_game_lol:"英雄联盟比赛",
        league_game_dota2:"DOTA2比赛",
        league_game_cs:"CS比赛",
        league_menu_unplayed:"未开始比赛",
        league_menu_doing:"进行中比赛",
        league_menu_end:"已结束比赛",
        league_title_team:"竞猜战队",
        league_title_type:"竞猜类型",
        league_title_odds:"竞猜赔率",
        league_title_time:"开赛时间",
        league_button_detail:"详情投注",
        league_button_analysis:"对战分析",
        league_button_competition:"竞猜",
        league_words_rule:"注意:请先阅读竞猜规则，竞猜后视为您同意遵守本规则",
        league_button_view:"点击查看",
        league_button_confirm_competition:"确定竞猜",
        league_button_confirm:"确定",
        league_button_cancel:"取消",
        league_words_guess:"竞猜",
        league_words_gold:"金币",
        league_words_rand:"随机填写",
        league_words_total:"共",
        league_words_odds:"赔率",
        league_words_expected:"预计可得",
        league_words_balance:"账户余额",
        league_words_tips:"温馨提示",
        league_tips_success:"投注成功",
        league_tips_failed:"投注失败",
        league_tips_not_login:"未登录",
        league_tips_invalid:"比赛无效",
        league_tips_end:"比赛已结束",
        league_tips_before:"开赛前五分钟，禁止投注",
        league_tips_min:"最小投注金额不能少于10金币",
        league_tips_requeried:"请输入金额",
        league_tips_balance:"金币不足，请充值",
        data_menu_match:"赛事",
        data_menu_team:"战队",
        data_menu_compare:"对战数据",
        data_words_all:"全部",
        data_words_hot:"热门",
        data_title_match:"赛事",
        data_title_detail:"赛事详情",
        data_title_introduce:"赛事介绍",
        data_title_enter_team:"参赛战队",
        data_title_schedule:"赛程",
        data_title_Sponsor:"主办方",
        data_title_System:"赛制",
        data_title_place:"举办地",
        data_title_bonus:"总奖金",
        data_title_world_ranking:"世界排名",
        data_title_team_name:"战队名称",
        data_title_area:"所在赛区",
        data_title_win_rate:"胜率",
        data_title_score:"战绩",
        data_title_coach:"教练",
        data_title_area_ranking:"赛区排名",
        data_title_members:"核心成员",
        data_words_time:"时间",
        data_time_all:"全部",
        data_time_three_month:"3个月",
        data_time_half_year:"半年",
        data_time_year:"一年",
        data_title_date:"比赛时间",
        data_title_team_against:"对阵",
        data_title_win_defeat:"胜负",
        data_title_times:"比赛时长",
        data_title_rt:"人头比",
        data_title_sd:"小龙",
        data_title_bd:"大龙",
        data_title_is_fb:"是否一血",
        data_title_is_ft:"是否一塔",
        data_button_compare:"对比",
        data_button_change:"更换",
        data_title_against:"两队历史对阵",
        data_title_history:"两队历史数据",
        data_words_site:"场",
        data_words_win:"胜",
        data_words_defeat:"负",
        data_words_site_numbers:"场数",
        data_words_win_rate:"胜率",
        data_title_fb:"1血",
        data_title_ft:"1塔",
        data_words_fetch_site:"获得场数",
        data_words_fetch_rate:"获取率",
        personal_title_total:"竞猜总数",
        personal_title_win:"胜利场数",
        personal_title_defeat:"失败场数",
        personal_title_rate:"胜率",
        personal_menu_day:"日收益",
        personal_menu_week:"周收益",
        personal_menu_month:"月收益",
        personal_menu_total:"总收益",
        personal_button_edit:"编辑资料",
        personal_button_mybet:"我的竞猜",
        personal_button_query:"查询",
        personal_button_reset:"重置",
        personal_button_recharge:"充值",
        personal_button_detail:"详情",
        personal_words_time:"时间",
        personal_words_time_from:"从",
        personal_words_time_to:"到",
        personal_words_nodata:"暂无收益记录",
        personal_title_time:"竞猜时间",
        personal_title_match:"赛事名称",
        personal_title_bo:"第几局",
        personal_title_team:"竞猜战队",
        personal_title_competition:"竞猜类型",
        personal_title_amount:"竞猜额度",
        personal_title_status:"开奖状态",
        personal_title_bet_time:"投注时间",
        personal_title_bet_team:"投注战队",
        personal_title_bet_comp:"竞猜内容",
        personal_title_bet_result:"竞猜结果",
        personal_title_team_name:"战队名称",
        personal_title_date:"日期",
        personal_title_option:"操作",
        personal_title_odds:"赔率",
        personal_title_game_type:"游戏类型",
        personal_words_gold:"金币",
        personal_words_total_income:"有效总收益",
        personal_title_bet_detail:"竞猜详情",
        personal_words_invalid:"无效",
        personal_tips_edits:"个人资料修改成功",
        personal_tips_editf:"个人资料修改失败，请核对信息后重试",
        personal_tips_success:"恭喜您，竞猜成功",
        personal_tips_failed:"很遗憾，您参与的竞猜未中奖",
        league_words_date:"日期",
        league_button_query:"查询",
        league_menu_all_match:"全部联赛",
        league_button_view_detail:"查看详情",
        league_title_win_team:"获胜战队",
        league_title_times:"比赛时长",
        league_title_fb_team:"一血战队",
        league_title_ft_team:"一塔战队",
        league_title_rt:"人头比",
        league_title_sd:"小龙",
        league_title_bd:"大龙",
        league_tips_max:"最大投注金额100000！",
        league_tips_system_error:"系统异常",
        league_words_gold_guess:"金币竞猜",
        league_words_join_user:"参与用户",
        league_words_mybet:"我的竞猜",
        league_title_sequence:"序列",
        league_title_match:"赛事名称",
        league_title_bo:"第几局",
        league_title_amount:"竞猜金额",
        league_title_order_no:"订单号",
        league_title_order_date:"订单时间",
        data_words_area:"赛区",
        league_words_join_guess:"参与竞猜",
        data_words_fetch_fb:"获取1血",
        data_words_fb_rate:"1血获取率",
        data_words_fetch_ft:"获取1塔",
        data_words_ft_rate:"1塔获取率",
        common_tips_system_error:"系统错误",
        data_words_query_team:"查找战队",
        data_words_no_team:"战队不存在",
        data_tips_two_teams:"请选择两个战队进行比较",
        data_title_team_introduce:"战队介绍",
        personal_words_bet_date:"投注日期",
        personal_words_lottery:"已开奖",
        personal_words_no_lottery:"未开奖",
        personal_tips_nodata:"当天没有竞猜数据",
        common_words_give:"新用户首次登录赠送200金币",
        data_words_di:"第",
        data_words_ju:"局",
        personal_center_pageself:"我的主页",
        personal_center_accName:"账户名称",
        personal_center_regTime:"注册时间",
        personal_center_accMoney:"账户余额",
        personal_center_info:"个人资料",
        personal_center_accRecharge:"账户充值",
        personal_center_rechargeList:"我的账单",
        personal_center_changeList:"兑换记录",
        personal_center_addrManage:"地址管理",
        personal_center_nickname:"昵称",
        personal_center_sex:"性别",
        personal_center_man:"男",
        personal_center_women:"女",
        personal_center_save:"保 存",
        personal_center_recharge:"充值",
        personal_center_nodata:"暂无数据",
        personal_center_rechargeTime:"时间",
        personal_center_detail:"详情",
        personal_center_amount:"金额",
        personal_center_cancel:"取 消",
        personal_center_orderno:"订单号",
        personal_center_traded:"交易成功",
        common_tip_message1:"提示：请输入昵称",
        common_tip_message2:"提示：昵称已被占用",
        common_tip_message3:"提示：昵称可用",
        common_tip_message4:"提示：昵称中包含非法字符",
        common_tip_message5:"提示：昵称超过最大长度",
        common_tip_message6:"温馨提示",
        common_tip_message7:"个人资料修改成功",
        common_tip_message8:"个人资料修改失败，请核对信息后重试",
        shoppingMall_words_soon:"商城近期开放，金币可兑换相应商品，敬请关注！",
        league_tips_param_error:"参数错误",
        league_tips_count_not_exists:"账户不存在",
        league_tips_balance_not_enouth:"账户可用余额不足",
        league_tips_bet_limitation:"投注额已达上限",
        common_footer_dxxk:"增值电信业务许可证",
        common_footer_dxxk_val:"粤B2-20160345",
        common_footer_cmxk:"互联网文化经营许可证",
        common_footer_cmxk_val:"粤网文[2016]1273-268号",
        common_footer_vedxk:"广播电视节目制作经营许可证",
        common_footer_vedxk_val:"粤字 第01837号",
        articleDetail_fontsize:"字体",
        articleDetail_big:"大",
        articleDetail_medium:"中",
        articleDetail_small:"小",
        data_match_not_start:"该赛事暂未开赛",
        league_words_nodata:"暂无竞猜记录",
        competitionRules_rules:"竞猜规则",
        personal_words_curr_total_income:"当页有效总收益",
        personal_words_income_date:"收益日期",
        common_words_yes:"是",
        common_words_no:"否",
        index_words_video:"视频中心",
        data_words_video:"视频",
        data_words_full_video:"完场视频",
        personal_menu_regist_date:"注册时间",
        personal_menu_today:"今日收益",
        personal_title_username:"帐号名称",
        personal_title_person_info:"个人资料",
        person_title_check_head:"选择头像",
        data_words_to:"至",
        data_title_rs:"肉山",
        shop_words_goods:"商品",
        shop_words_list:"商品清单",
        shop_words_num:"数量",
        shop_words_price:"价格",
        shop_words_rule:"我同意《游戏竞猜金币兑换协议》",
        shop_words_address:"收货信息",
        shop_words_tip:"提示：此商品不限购买数\!",
        shop_words_buy:"立即购买",
        shop_words_new_addresss:"使用新地址",
        shop_words_exchange:"兑换信息",
        data_game_code_name_lol:"英雄联盟",
        data_game_code_name_dota2:"DOTA2",
        personal_title_income:"纯收益",
        personal_order_date:"兑换日期",
        personal_order_goods_name:"商品名称",
        personal_order_goods_count:"兑换数量",
        personal_order_title:"商品单号",
        personal_order_coin:"成交金币",
        personal_order_status:"状态",
        op_message_success:"操作成功",
        op_message_error:"操作失败",
        common_words_platform:"乐盈电竞",
        match_word_all:"全部赛事",
        match_menu_doing:"竞猜中",
        match_menu_end:"已结束",
        popup_bet_balance:"可用余额",
        popup_bet_title:"竞猜投注",
        popup_bet_coin:"投注额",
        popup_bet_least:"最少投注",
        popup_bet_pre_win_coin:"可获得金币",
        popup_bet_bet_button:"立即投注",
        match_number_one:"一",
        match_number_two:"二",
        match_number_three:"三",
        match_number_four:"四",
        match_number_five:"五",
        match_number_six:"六",
        match_number_total:"总",
        guess_end_headers:"人头数",
        guess_end_last_hits:"补刀数",
        guess_end_helps:"助攻数",
        guess_end_hit_towers:"破塔数",
        guess_end_first_bloods:"一血",
        guess_end_first_tower:"一塔",
        guess_end_first_little_dragon:"第一条小龙",
        guess_end_first_big_dragon:"第一条大龙",
        guess_end_first_roushan:"第一座肉山",
        guess_end_first_boss:"第一只BOSS",
        guess_end_first_bj:"第一只暴君",
        guess_end_first_zz:"第一只主宰",
        data_game_code_name_cf:"穿越火线",
        data_game_code_name_ow:"守望先锋",
        data_game_code_name_hearthstone:"炉石传说",
        data_game_code_name_kg:"王者荣耀",
        data_game_code_name_cos:"英魂之刃",
        personal_words_no_settle:"未结算",
        personal_words_has_settle:"已结算",
        personal_words_has_return:"已退回",
        guess_other_play:"其他玩法",
        guess_big:"大",
        guess_little:"小",
        guess_simple:"单",
        guess_double:"双",
        guess_greater_that:"大于",
        guess_less_that:"小于",
        common_header_competition_hall:"竞猜大厅",
        common_header_information:"资讯",
        common_header_game_platform:"游戏平台",
        match_play_introduction:"玩法介绍",
        index_words_hot_match:"热门赛事",
        index_words_hot_competition:"热门竞猜",
        index_words_news_information:"新闻资讯",
        common_words_hot_information:"热点资讯",
        common_words_news_center:"新闻中心",
        personal_title_recharge_details:"充值明细",
        personal_words_invalid_tips:"因赛程调整导致该比赛取消",
        personal_words_back_tips:"您的投注金额已经退回您的账户",
        match_end_cf_map:"使用地图",
        match_end_cf_time:"耗时",
        match_end_cf_mode:"模式",
        match_end_cf_kill:"击杀",
        match_end_cf_round:"回合数",
        match_end_ow_zd:"占点比",
        match_end_ow_mvp:"最佳",
        match_end_csgo_ct:"CT",
        match_end_csgo_t:"T",
        index_news_center:"赛事中心",
        popup_bet_income_coin:"纯收益",
        data_title_match_times:"比赛场数",
        personal_center_sign:"签到",
        personal_center_signed:"已签到",
        data_title_first_tower:"",
        data_title_first_roushan:"一肉山率",
        data_title_avg_kda:"KDA",
        data_of_month:"月",
        data_of_day:"day",
        account_is_locked:"account is locked",
        competition_not_exist:"competition not exist",
        competition_not_betting:"competition not betting\\"
    };

    //国际化
    var gjh ={
        common_button_previous : '上一页',
        common_button_next : '下一页',
        common_words_di : '第',
        common_words_ye : '页',

        league_tips_not_login : '未登录',
        common_words_nodata : '暂无数据',
        league_words_guess : '竞猜',
        league_words_gold : '金币',
        league_words_tips : '温馨提示',
        league_tips_min : '最小投注金额不能少于10金币',
        league_tips_max : '最大投注金额100000！',
        league_tips_before : '开赛前五分钟，禁止投注',

        league_tips_balance : '金币不足，请充值',
        personal_button_recharge : '充值',
        league_tips_success : '投注成功',
        league_tips_requeried : '请输入金额',
        league_tips_failed : '投注失败',
        league_tips_system_error : '系统异常',
        data_words_all : '全部',
        data_words_hot : '热门',

        personal_words_nodata : '暂无收益记录',
        data_words_win : '胜',
        data_words_defeat : '负',
        personal_words_invalid : '无效',
        personal_words_gold : '金币',
        personal_words_total_income : '有效总收益',
        personal_button_detail : '详情',
        personal_words_lottery : '已开奖',
        personal_words_no_lottery : '未开奖',
        personal_tips_nodata : '当天没有竞猜数据',
        data_words_di : '第',
        data_words_ju : '局',
        personal_center_nodata : '暂无数据',
        personal_center_orderno : '订单号',
        personal_center_traded : '交易成功',
        common_button_confirm : '确 定',


        common_tip_message1 : '提示：请输入昵称',
        common_tip_message2 : '提示：昵称已被占用',
        common_tip_message3 : '提示：昵称可用',
        common_tip_message4 : '提示：昵称中包含非法字符',
        common_tip_message5 : '提示：昵称超过最大长度',
        common_tip_message6 : '温馨提示',
        common_tip_message7 : '个人资料修改成功',
        common_tip_message8 : '个人资料修改失败，请核对信息后重试',
        common_tips_system_error : '系统错误',

        common_words_soon : '敬请期待',
        op_message_success : '操作成功',
        op_message_error : '操作失败',


        league_tips_param_error : '参数错误',
        league_tips_count_not_exists : '账户不存在',
        league_tips_balance_not_enouth : '账户可用余额不足',
        league_tips_bet_limitation : '投注额已达上限',

        personal_words_curr_total_income : '当页有效总收益',
        /******************国际化游戏名称*******************/
        data_game_code_name_lol : '英雄联盟',
        data_game_code_name_cf : '穿越火线',
        data_game_code_name_ow : '守望先锋',
        data_game_code_name_dota2 : 'DOTA2',
        data_game_code_name_hearthstone : '炉石传说',
        data_game_code_name_csgo : 'CSGO',
        data_game_code_name_kg : '王者荣耀',
        data_game_code_name_cos : '英魂之刃',

        popup_bet_balance : '可用余额',
        match_number_one : '一',
        match_number_two : '二',
        match_number_three : '三',
        match_number_four : '四',
        match_number_five : '五',
        match_number_six : '六',
        match_number_total : '总',

        guess_other_play : '其他玩法',
        guess_big : '大',
        guess_little : '小',
        guess_simple : '单',
        guess_double : '双',
        guess_greater_that : '大于',
        guess_less_that : '小于',

        common_words_give : '新用户首次登录赠送200金币',
        league_button_confirm : '确定',
        league_button_cancel : '取消',
        common_header_log_out : '退出',
        personal_center_recharge : '充值',
        index_words_end : '已结束',
        index_title_video : '观看记录',
        index_button_competition : '比赛竞猜',
        data_tips_two_teams : '请选择两个战队进行比较',
        common_words_no_open : '暂未开放',

        personal_center_sign : '签到',
        personal_center_signed : '已签到',

        account_is_locked : '该账户已锁定',
        competition_not_exist : '该竞猜无效或不存在',
        competition_not_betting : '该竞猜已停盘',
    }
    var all={};
    all["cn"]=langue;
    function lg(key,type) {
        //语言
        if(!type){
            type="cn";
        }
        if(all[type]&&all[type][key]){
            return all[type][key];
        }
        return "";
    }

    return {
        lg: lg,
        gjh:gjh
    }
})()